const APPEND_TAB = 'Dashboard/APPEND_TAB';
const RESET_TAB = 'Dashboard/RESET_TAB';
const SWITCH_TAB = 'Dashboard/SWITCH_TAB';
const DELETE_TAB = 'Dashboard/DELETE_TAB';
const DELETE_OTHER = 'Dashboard/DELETE_OTHER';
const DELETE_ALL = 'Dashboard/DELETE_All';

const APPEND_NOTIFY = 'Dashboard/APPEND_NOTIFY';
const USER_LOGIN = 'Dashboard/USER_LOGIN';

const UPDATE_TIME_AGO = 'Dashboard/UPDATE_TIME_AGO';

const SET_DATA_NOTIFY_USER = 'Dashboard/SET_DATA_NOTIFY_USER';
export {
  APPEND_TAB,
  RESET_TAB,
  SWITCH_TAB,
  DELETE_TAB,
  DELETE_OTHER,
  DELETE_ALL,
  APPEND_NOTIFY,
  UPDATE_TIME_AGO,
  USER_LOGIN,
  SET_DATA_NOTIFY_USER,
};
