# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD

on:
  push:
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Go to project and pull code 
      run: |
        cd D:\AUTONSI\Projects\Hanlim\HaeSung-Fe-master
        yarn install
        yarn build2
    - name: Copy file publish to serve
      uses: garygrossgarten/github-action-scp@release
      with:
        local: D:\AUTONSI\Projects\Hanlim\HaeSung-Fe-master\public
        remote: D:\Autonsi Cloud Backup\Solution\test
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
